
setx /M XDBGNI_TESTFLDR C:\TEST\XDBGNI\ 
setx /M XDBGX64_PATH C:\_TOOLS_\_RCE_\XDBG\GHDBG\x64 
setx /M XDBGX32_PATH C:\_TOOLS_\_RCE_\XDBG\GHDBG\x32

pause

setx /M PRJBUILDDIR C:\_BUILD
setx /M GITCMMNDIR C:\_BUILD\.git
setx /M COMMONSRCDIR C:\_SYNC\COMMONSRC\SimpleCommon

pause