
setx /M XDBGNI_TESTFLDR C:\TEST\XDBGNI\ 
setx /M XDBGX64_PATH C:\_TOOLS_\_RCE_\DBGx64 
setx /M XDBGX32_PATH C:\_TOOLS_\_RCE_\DBGx32


setx /M PRJBUILDDIR C:\BUILD
setx /M GITCMMNDIR C:\BUILD\.git
setx /M COMMONSRCDIR C:\WORKFOLDER\_COMMONSRC_\SimpleCommon

pause